---
title: "Supervised Independent Study and Research"
subtitle: "STAT 199, Spring 2025"
---

This is the companion website for __STAT 199 Supervised Independent Study and Research__ (Spring 2025) under the supervision of <a href="https://www.gastonsanchez.com" target="_blank">Gaston Sanchez</a>, at UC Berkeley.

\

## Spring 2025 Calendar

Tentative calendar subject to change.

| Date    | Session                                                         | Meetings |
|---------|-----------------------------------------------------------------|----------|
|  1/21   | [1) Introduction](modules/mod01-introduction.html)              | [meet 1](meetings/m01-introduction.html) |
|  1/28   | [2) IBTrACS Data](modules/mod02-data.html)                      | log 2    |
|  2/05   | [3) EDA Single Basin](modules/mod03-eda-single-basin.html)      | log 3    |
|  2/12   | [4) Mapping Storm Tracks](modules/mod04-mapping-tracks)         | log 4    |
|  2/19   | [5) Quarto Websites I](modules/mod05-quarto-website1.html)      | log 5    |
|  2/26   | [6) Quarto Websites II](modules/mod06-quarto-website2.html)     | log 6    |
|  3/05   | [7) Closeread Documents I](modules/mod07-closeread-docs1.html)  | log 7    |
|  3/12   | [8) Closeread Documents II](modules/mod08-closeread-docs2.html) | log 8    |
|  3/19   | 9) Animations | log 9 | 
|  3/26   | _Spring Recess_     | |
|  4/02   | 10) Shiny App       | log 10   |
|  4/09   | 11) TBD             | log 11   |
|  4/16   | 12) TBD             | log 12   |
|  4/23   | 13) TBD             | log 13   |


